import Head from "next/head";
import Link from "next/link";
import { auth, useUser } from '@clerk/nextjs'
import { SignInButton, SignOutButton } from "@clerk/nextjs";
import { RouterOutputs, api } from "~/utils/api";
import Image from "next/image";
import dayjs from "dayjs"
import relativeTime from "dayjs/plugin/relativeTime"

dayjs.extend(relativeTime)

const CreatePostWizard = () => {
  const { user } = useUser()
  console.log(user);

  if (!user) return null

  return <div className="w-full flex gap-3">
    <Image
      src={user.profileImageUrl}
      alt="Profile Image"
      className="w-14 h-14 rounded-full"
      width={56}
      height={56}
    />
    <input placeholder="Type some emojis..." className="bg-transparent grow outline-none" />
  </div>
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number]
const PostView = (props: PostWithUser) => {
  const { post, author } = props
  return (
    <div key={post.id} className="p-4 border-b border-slate-400 flex gap-3">
      <Image
        src={author.profileImageUrl}
        alt={`${author.firstName}'s profile picture`}
        className="w-14 h-14 rounded-full"
        width={56}
        height={56}
      />
      <div className="flex flex-col">
        <div className="flex gap-1 text-slate-300">
          <span>{`@${author.firstName}`}</span>
          <span className="font-thin text-slate-400">{`· ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

export default function Home() {

  const user = useUser()
  const { data, isLoading } = api.posts.getAll.useQuery()
  if (isLoading) return <div>Loading...</div>
  if (!data) return <div>Something went wrong</div>
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-center">
        <div className="w-full md:max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {[...data, ...data]?.map((fullPost) =>
              <PostView {...fullPost} key={fullPost.post.id} />
            )}
          </div>
        </div>
      </main>
    </>
  )
}